export enum User_Notif_Type {
    NEW_POST = 'NEW_POST',
    SUBMISSION = 'SUBMISSION',
    GRADED_POST = 'GRADED_POST',
    FRIEND_REQUEST = 'FRIEND_REQUEST',
    FRIEND_RESPONSE = 'FRIEND_RESPONSE',
    REPORT = 'REPORT',
    SYSTEM = 'SYSTEM',
}