import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1790959192808 implements MigrationInterface {
    name = 'InitialSchema1790959192808'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "app_config" ("key" character varying(64) NOT NULL, "value" character varying(255) NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_e53f3c7882ebd6e79931e0fa959" PRIMARY KEY ("key"))`);
        await queryRunner.query(`CREATE TABLE "question_preparation_collection" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" uuid, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" uuid, "deleted_at" TIMESTAMP WITH TIME ZONE, "deleted_by" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(50) NOT NULL, "desc" character varying(100), "user_id" uuid, CONSTRAINT "PK_7c5e2858eeb13778bb0ffc9f857" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_348b427161dc30f5c7bfe6f52c" ON "question_preparation_collection"  ("user_id") `);
        await queryRunner.query(`CREATE TABLE "question_preparation" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" uuid, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" uuid, "deleted_at" TIMESTAMP WITH TIME ZONE, "deleted_by" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(50) NOT NULL, "content" jsonb NOT NULL, "correct_answer" jsonb, "user_id" uuid, "collection_id" uuid, CONSTRAINT "PK_3ac101e89977150960fe00c2a70" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7c5e2858eeb13778bb0ffc9f85" ON "question_preparation"  ("collection_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f11504860f2f8598340f3092f7" ON "question_preparation"  ("created_by") `);
        await queryRunner.query(`CREATE TYPE "public"."group_member_role_enum" AS ENUM('ADMIN', 'MEMBER', 'FOUNDER')`);
        await queryRunner.query(`CREATE TABLE "group_member" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" uuid, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" uuid, "deleted_at" TIMESTAMP WITH TIME ZONE, "deleted_by" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "role" "public"."group_member_role_enum" NOT NULL DEFAULT 'MEMBER', "rejoin_at" TIMESTAMP WITH TIME ZONE, "user_id" uuid, "group_id" uuid, CONSTRAINT "PK_65634517a244b69a8ef338d03c3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4e21968f2f777c87874d5c5f53" ON "group_member"  ("group_id", "user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."group_join_request_status_enum" AS ENUM('PENDING', 'REJECTED', 'APPROVED')`);
        await queryRunner.query(`CREATE TABLE "group_join_request" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" uuid, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" uuid, "deleted_at" TIMESTAMP WITH TIME ZONE, "deleted_by" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" "public"."group_join_request_status_enum" NOT NULL DEFAULT 'PENDING', "reviewed_at" TIMESTAMP WITH TIME ZONE, "sender_id" uuid, "group_id" uuid, "reviewer_id" uuid, CONSTRAINT "PK_caaeca0272d5b59e74ca74c9c83" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_group_join_request_group_sender" ON "group_join_request"  ("group_id", "sender_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_group_join_request_sender_group" ON "group_join_request"  ("sender_id", "group_id", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."post_answer_status_enum" AS ENUM('PENDING', 'COMPLETED')`);
        await queryRunner.query(`CREATE TABLE "post_answer" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" uuid, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" uuid, "deleted_at" TIMESTAMP WITH TIME ZONE, "deleted_by" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "answer_content" jsonb NOT NULL, "point" double precision, "max_point" double precision, "graded_at" TIMESTAMP WITH TIME ZONE, "review_content" jsonb, "status" "public"."post_answer_status_enum" NOT NULL DEFAULT 'PENDING', "user_id" uuid, "post_id" uuid, "group_id" uuid, "graded_by" uuid, CONSTRAINT "PK_eed6549ccbd0ec50cb503475e8f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6434de71e37c4f3356d1d7f0fb" ON "post_answer"  ("group_id", "post_id", "user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."post_retake_enum" AS ENUM('BEFORE', 'NEVER')`);
        await queryRunner.query(`CREATE TYPE "public"."post_view_each_other_answer_enum" AS ENUM('AFTER_ANSWER', 'AFTER_DEADLINE', 'NEVER')`);
        await queryRunner.query(`CREATE TABLE "post" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" uuid, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" uuid, "deleted_at" TIMESTAMP WITH TIME ZONE, "deleted_by" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(50) NOT NULL, "description" text, "content" jsonb NOT NULL, "correct_answer" jsonb, "deadline_at" TIMESTAMP WITH TIME ZONE, "retake" "public"."post_retake_enum" NOT NULL DEFAULT 'NEVER', "view_each_other_answer" "public"."post_view_each_other_answer_enum" NOT NULL DEFAULT 'NEVER', "user_id" uuid, "group_id" uuid, "post_collection_id" uuid, CONSTRAINT "PK_be5fda3aac270b134ff9c21cdee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d87f356ee0cfdb6167af165f06" ON "post"  ("post_collection_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "post_collection" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" uuid, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" uuid, "deleted_at" TIMESTAMP WITH TIME ZONE, "deleted_by" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(50) NOT NULL, "desc" character varying(100), "group_id" uuid, CONSTRAINT "PK_a176e95fb667b6b865d36136967" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b2b341ff8d6b0df3cf8f464aa3" ON "post_collection"  ("group_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d85c479a04332bb7aa4e0d8d4e" ON "post_collection"  ("created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."group_join_mode_enum" AS ENUM('BY_REQUEST', 'PUBLIC')`);
        await queryRunner.query(`CREATE TYPE "public"."group_view_mode_enum" AS ENUM('PRIVATE', 'PUBLIC')`);
        await queryRunner.query(`CREATE TABLE "group" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" uuid, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" uuid, "deleted_at" TIMESTAMP WITH TIME ZONE, "deleted_by" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying(50) NOT NULL, "name" character varying(50) NOT NULL, "description" character varying(500), "join_mode" "public"."group_join_mode_enum" NOT NULL DEFAULT 'BY_REQUEST', "view_mode" "public"."group_view_mode_enum" NOT NULL DEFAULT 'PRIVATE', "founder_id" uuid, CONSTRAINT "UQ_d3240eaf64d34439513e46cb495" UNIQUE ("slug"), CONSTRAINT "PK_256aa0fda9b1de1a73ee0b7106b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_29c661cb5d517263393258e584" ON "group"  ("founder_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d3240eaf64d34439513e46cb49" ON "group"  ("slug") `);
        await queryRunner.query(`CREATE TABLE "friendship" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" uuid, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" uuid, "deleted_at" TIMESTAMP WITH TIME ZONE, "deleted_by" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "be_friend_at" TIMESTAMP WITH TIME ZONE NOT NULL, "user_id" uuid, "friend_id" uuid, "source_request_id" uuid, CONSTRAINT "PK_dbd6fb568cd912c5140307075cc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ad1ce18bf3d2087495b0ef0b26" ON "friendship"  ("user_id", "friend_id", "be_friend_at") `);
        await queryRunner.query(`CREATE TYPE "public"."friend_request_status_enum" AS ENUM('PENDING', 'REJECTED', 'ACCEPTED', 'SELF_CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "friend_request" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" uuid, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" uuid, "deleted_at" TIMESTAMP WITH TIME ZONE, "deleted_by" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" "public"."friend_request_status_enum" NOT NULL DEFAULT 'PENDING', "sender_id" uuid, "receiver_id" uuid, CONSTRAINT "PK_4c9d23ff394888750cf66cac17c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_37d2ace7f95c1dd0ae665a570d" ON "friend_request"  ("sender_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6f327bd90aba348e276d42ecf2" ON "friend_request"  ("receiver_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ae818ef103755c30885c5294ef" ON "friend_request"  ("sender_id", "receiver_id") `);
        await queryRunner.query(`CREATE TYPE "public"."user_notif_type_enum" AS ENUM('NEW_POST', 'GRADED_POST', 'GROUP_JOIN_REQUEST', 'GROUP_JOIN_APPROVED', 'GROUP_JOIN_REJECTED', 'GROUP_MEMBER_KICKED', 'GROUP_MEMBER_ROLE_CHANGED', 'FRIEND_REQUEST', 'FRIEND_RESPONSE', 'SUBMISSION', 'REPORT_RESOLVED', 'REPORT', 'SYSTEM')`);
        await queryRunner.query(`CREATE TABLE "user_notif" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" uuid, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" uuid, "deleted_at" TIMESTAMP WITH TIME ZONE, "deleted_by" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."user_notif_type_enum" NOT NULL, "content" jsonb NOT NULL, "is_read" boolean NOT NULL DEFAULT false, "user_id" uuid, CONSTRAINT "PK_45fcfbf6d32f4cb196a8e4e0631" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "notif_user_created_at" ON "user_notif"  ("user_id", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."report_target_type_enum" AS ENUM('POST', 'USER', 'GROUP', 'POST_ANSWER')`);
        await queryRunner.query(`CREATE TYPE "public"."report_reason_enum" AS ENUM('SPAM', 'INAPPROPRIATE_CONTENT', 'HARASSMENT', 'OFF_TOPIC', 'OTHER')`);
        await queryRunner.query(`CREATE TYPE "public"."report_status_enum" AS ENUM('PENDING', 'REVIEWING', 'RESOLVED', 'REJECTED')`);
        await queryRunner.query(`CREATE TYPE "public"."report_action_taken_enum" AS ENUM('NONE', 'CONTENT_REMOVED', 'USER_WARNED', 'USER_FROZEN', 'GROUP_CLOSED')`);
        await queryRunner.query(`CREATE TABLE "report" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" uuid, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" uuid, "deleted_at" TIMESTAMP WITH TIME ZONE, "deleted_by" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "target_type" "public"."report_target_type_enum" NOT NULL, "target_id" uuid NOT NULL, "reason" "public"."report_reason_enum" NOT NULL, "description" text NOT NULL, "status" "public"."report_status_enum" NOT NULL DEFAULT 'PENDING', "action_taken" "public"."report_action_taken_enum", "reviewed_at" TIMESTAMP WITH TIME ZONE, "review_note" text, "user_id" uuid, "reviewed_by" uuid, CONSTRAINT "PK_99e4d0bea58cba73c57f935a546" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fc86d216c30504f7f4b9e32d32" ON "report"  ("status", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_7f1f929604d4e33f5c64612ac6" ON "report"  ("target_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2da9593ed53c3aea38739f8a2c" ON "report"  ("created_at") `);
        await queryRunner.query(`CREATE TABLE "refresh_token" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" uuid, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" uuid, "deleted_at" TIMESTAMP WITH TIME ZONE, "deleted_by" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "jti" character varying NOT NULL, "token_hash" character varying(257) NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "revoked_at" TIMESTAMP WITH TIME ZONE, "device" text, "ip_address" text, "user_id" uuid, "replaced_by" uuid, CONSTRAINT "UQ_e532a5fe469da358494917ce2bf" UNIQUE ("jti"), CONSTRAINT "REL_8564f8a18554b67aafe4ef50be" UNIQUE ("replaced_by"), CONSTRAINT "PK_b575dd3c21fb0831013c909e7fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e532a5fe469da358494917ce2b" ON "refresh_token"  ("jti") `);
        await queryRunner.query(`CREATE INDEX "IDX_f0812282fad2e352cdaf83ef0a" ON "refresh_token"  ("token_hash") `);
        await queryRunner.query(`CREATE TYPE "public"."user_role_enum" AS ENUM('USER', 'SYSTEM_ADMIN')`);
        await queryRunner.query(`CREATE TYPE "public"."user_status_enum" AS ENUM('ACTIVE', 'BANNED')`);
        await queryRunner.query(`CREATE TABLE "user" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" uuid, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" uuid, "deleted_at" TIMESTAMP WITH TIME ZONE, "deleted_by" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "role" "public"."user_role_enum" NOT NULL DEFAULT 'USER', "user_name" character varying(50), "email" text NOT NULL, "password" text, "google_id" character varying(64), "nickname" character varying(50) NOT NULL, "bio" character varying(100), "avatar_url" text, "status" "public"."user_status_enum" NOT NULL DEFAULT 'ACTIVE', "status_changed_at" TIMESTAMP WITH TIME ZONE, "status_changed_by" uuid, CONSTRAINT "UQ_d34106f8ec1ebaf66f4f8609dd6" UNIQUE ("user_name"), CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "UQ_7adac5c0b28492eb292d4a93871" UNIQUE ("google_id"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d34106f8ec1ebaf66f4f8609dd" ON "user"  ("user_name") `);
        await queryRunner.query(`CREATE INDEX "IDX_e12875dfb3b1d92d7d7c5377e2" ON "user"  ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_d091f1d36f18bbece2a9eabc6e" ON "user"  ("created_at") `);
        await queryRunner.query(`CREATE TABLE "forget_password_otp" ("created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" uuid, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" uuid, "deleted_at" TIMESTAMP WITH TIME ZONE, "deleted_by" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(6) NOT NULL, "is_pass_otp" boolean NOT NULL DEFAULT false, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "user_id" uuid, CONSTRAINT "PK_62927108cb284339892801ed279" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9b77eebe437d4e3eabb7282033" ON "forget_password_otp"  ("code") `);
        await queryRunner.query(`CREATE TABLE "storage_object" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying NOT NULL, "url" character varying NOT NULL, "ref_count" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_26e87f38b54699165c3ea5831a1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2a37c931c28ea822252a082969" ON "storage_object"  ("key") `);
        await queryRunner.query(`ALTER TABLE "question_preparation_collection" ADD CONSTRAINT "FK_348b427161dc30f5c7bfe6f52ca" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "question_preparation" ADD CONSTRAINT "FK_ad4d2add26de5498feededa8d85" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "question_preparation" ADD CONSTRAINT "FK_7c5e2858eeb13778bb0ffc9f857" FOREIGN KEY ("collection_id") REFERENCES "question_preparation_collection"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_member" ADD CONSTRAINT "FK_b2bc36d5183cc323a0223f9114c" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_member" ADD CONSTRAINT "FK_e200cd6ff3e3903c5be5ae1400e" FOREIGN KEY ("group_id") REFERENCES "group"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_join_request" ADD CONSTRAINT "FK_7ff03a33abf7aed19ee80fc600a" FOREIGN KEY ("sender_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_join_request" ADD CONSTRAINT "FK_74818bd447ad642e13059b43849" FOREIGN KEY ("group_id") REFERENCES "group"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_join_request" ADD CONSTRAINT "FK_64f8afa7ad79637a2ff04eb9f5a" FOREIGN KEY ("reviewer_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_answer" ADD CONSTRAINT "FK_fa22451f5707d54c16f6eed2feb" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_answer" ADD CONSTRAINT "FK_efa0cb829358863a32467209cca" FOREIGN KEY ("post_id") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_answer" ADD CONSTRAINT "FK_ab0414eada16b3e92c8cb2a85a6" FOREIGN KEY ("group_id") REFERENCES "group"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_answer" ADD CONSTRAINT "FK_8d905c648b04edeb13aa3c29968" FOREIGN KEY ("graded_by") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post" ADD CONSTRAINT "FK_52378a74ae3724bcab44036645b" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post" ADD CONSTRAINT "FK_6d0d5abc465edbc42e054d0bb75" FOREIGN KEY ("group_id") REFERENCES "group"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post" ADD CONSTRAINT "FK_b2591a9471aeb8f8976e5a933a2" FOREIGN KEY ("post_collection_id") REFERENCES "post_collection"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_collection" ADD CONSTRAINT "FK_b2b341ff8d6b0df3cf8f464aa34" FOREIGN KEY ("group_id") REFERENCES "group"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group" ADD CONSTRAINT "FK_29c661cb5d517263393258e5843" FOREIGN KEY ("founder_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "friendship" ADD CONSTRAINT "FK_8885973a7c761a7f8fc0fc673f6" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "friendship" ADD CONSTRAINT "FK_8cadaad5534dd8b4827f05968ef" FOREIGN KEY ("friend_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "friendship" ADD CONSTRAINT "FK_c5c7c831ea767e9d824b21525ef" FOREIGN KEY ("source_request_id") REFERENCES "friend_request"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "friend_request" ADD CONSTRAINT "FK_37d2ace7f95c1dd0ae665a570dd" FOREIGN KEY ("sender_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "friend_request" ADD CONSTRAINT "FK_6f327bd90aba348e276d42ecf22" FOREIGN KEY ("receiver_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_notif" ADD CONSTRAINT "FK_24b0f30a4ec232a850478243608" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report" ADD CONSTRAINT "FK_c6686efa4cd49fa9a429f01bac8" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report" ADD CONSTRAINT "FK_68435e4be0139a4ee09de5ed80d" FOREIGN KEY ("reviewed_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_token" ADD CONSTRAINT "FK_6bbe63d2fe75e7f0ba1710351d4" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_token" ADD CONSTRAINT "FK_8564f8a18554b67aafe4ef50bea" FOREIGN KEY ("replaced_by") REFERENCES "refresh_token"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_182c1b156987cb0db12fa29bf1e" FOREIGN KEY ("status_changed_by") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forget_password_otp" ADD CONSTRAINT "FK_05ff5fc27c5ae0e93196f7062c2" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "forget_password_otp" DROP CONSTRAINT "FK_05ff5fc27c5ae0e93196f7062c2"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_182c1b156987cb0db12fa29bf1e"`);
        await queryRunner.query(`ALTER TABLE "refresh_token" DROP CONSTRAINT "FK_8564f8a18554b67aafe4ef50bea"`);
        await queryRunner.query(`ALTER TABLE "refresh_token" DROP CONSTRAINT "FK_6bbe63d2fe75e7f0ba1710351d4"`);
        await queryRunner.query(`ALTER TABLE "report" DROP CONSTRAINT "FK_68435e4be0139a4ee09de5ed80d"`);
        await queryRunner.query(`ALTER TABLE "report" DROP CONSTRAINT "FK_c6686efa4cd49fa9a429f01bac8"`);
        await queryRunner.query(`ALTER TABLE "user_notif" DROP CONSTRAINT "FK_24b0f30a4ec232a850478243608"`);
        await queryRunner.query(`ALTER TABLE "friend_request" DROP CONSTRAINT "FK_6f327bd90aba348e276d42ecf22"`);
        await queryRunner.query(`ALTER TABLE "friend_request" DROP CONSTRAINT "FK_37d2ace7f95c1dd0ae665a570dd"`);
        await queryRunner.query(`ALTER TABLE "friendship" DROP CONSTRAINT "FK_c5c7c831ea767e9d824b21525ef"`);
        await queryRunner.query(`ALTER TABLE "friendship" DROP CONSTRAINT "FK_8cadaad5534dd8b4827f05968ef"`);
        await queryRunner.query(`ALTER TABLE "friendship" DROP CONSTRAINT "FK_8885973a7c761a7f8fc0fc673f6"`);
        await queryRunner.query(`ALTER TABLE "group" DROP CONSTRAINT "FK_29c661cb5d517263393258e5843"`);
        await queryRunner.query(`ALTER TABLE "post_collection" DROP CONSTRAINT "FK_b2b341ff8d6b0df3cf8f464aa34"`);
        await queryRunner.query(`ALTER TABLE "post" DROP CONSTRAINT "FK_b2591a9471aeb8f8976e5a933a2"`);
        await queryRunner.query(`ALTER TABLE "post" DROP CONSTRAINT "FK_6d0d5abc465edbc42e054d0bb75"`);
        await queryRunner.query(`ALTER TABLE "post" DROP CONSTRAINT "FK_52378a74ae3724bcab44036645b"`);
        await queryRunner.query(`ALTER TABLE "post_answer" DROP CONSTRAINT "FK_8d905c648b04edeb13aa3c29968"`);
        await queryRunner.query(`ALTER TABLE "post_answer" DROP CONSTRAINT "FK_ab0414eada16b3e92c8cb2a85a6"`);
        await queryRunner.query(`ALTER TABLE "post_answer" DROP CONSTRAINT "FK_efa0cb829358863a32467209cca"`);
        await queryRunner.query(`ALTER TABLE "post_answer" DROP CONSTRAINT "FK_fa22451f5707d54c16f6eed2feb"`);
        await queryRunner.query(`ALTER TABLE "group_join_request" DROP CONSTRAINT "FK_64f8afa7ad79637a2ff04eb9f5a"`);
        await queryRunner.query(`ALTER TABLE "group_join_request" DROP CONSTRAINT "FK_74818bd447ad642e13059b43849"`);
        await queryRunner.query(`ALTER TABLE "group_join_request" DROP CONSTRAINT "FK_7ff03a33abf7aed19ee80fc600a"`);
        await queryRunner.query(`ALTER TABLE "group_member" DROP CONSTRAINT "FK_e200cd6ff3e3903c5be5ae1400e"`);
        await queryRunner.query(`ALTER TABLE "group_member" DROP CONSTRAINT "FK_b2bc36d5183cc323a0223f9114c"`);
        await queryRunner.query(`ALTER TABLE "question_preparation" DROP CONSTRAINT "FK_7c5e2858eeb13778bb0ffc9f857"`);
        await queryRunner.query(`ALTER TABLE "question_preparation" DROP CONSTRAINT "FK_ad4d2add26de5498feededa8d85"`);
        await queryRunner.query(`ALTER TABLE "question_preparation_collection" DROP CONSTRAINT "FK_348b427161dc30f5c7bfe6f52ca"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2a37c931c28ea822252a082969"`);
        await queryRunner.query(`DROP TABLE "storage_object"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9b77eebe437d4e3eabb7282033"`);
        await queryRunner.query(`DROP TABLE "forget_password_otp"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d091f1d36f18bbece2a9eabc6e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e12875dfb3b1d92d7d7c5377e2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d34106f8ec1ebaf66f4f8609dd"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TYPE "public"."user_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."user_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f0812282fad2e352cdaf83ef0a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e532a5fe469da358494917ce2b"`);
        await queryRunner.query(`DROP TABLE "refresh_token"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2da9593ed53c3aea38739f8a2c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7f1f929604d4e33f5c64612ac6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fc86d216c30504f7f4b9e32d32"`);
        await queryRunner.query(`DROP TABLE "report"`);
        await queryRunner.query(`DROP TYPE "public"."report_action_taken_enum"`);
        await queryRunner.query(`DROP TYPE "public"."report_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."report_reason_enum"`);
        await queryRunner.query(`DROP TYPE "public"."report_target_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."notif_user_created_at"`);
        await queryRunner.query(`DROP TABLE "user_notif"`);
        await queryRunner.query(`DROP TYPE "public"."user_notif_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ae818ef103755c30885c5294ef"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6f327bd90aba348e276d42ecf2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_37d2ace7f95c1dd0ae665a570d"`);
        await queryRunner.query(`DROP TABLE "friend_request"`);
        await queryRunner.query(`DROP TYPE "public"."friend_request_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ad1ce18bf3d2087495b0ef0b26"`);
        await queryRunner.query(`DROP TABLE "friendship"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d3240eaf64d34439513e46cb49"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_29c661cb5d517263393258e584"`);
        await queryRunner.query(`DROP TABLE "group"`);
        await queryRunner.query(`DROP TYPE "public"."group_view_mode_enum"`);
        await queryRunner.query(`DROP TYPE "public"."group_join_mode_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d85c479a04332bb7aa4e0d8d4e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b2b341ff8d6b0df3cf8f464aa3"`);
        await queryRunner.query(`DROP TABLE "post_collection"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d87f356ee0cfdb6167af165f06"`);
        await queryRunner.query(`DROP TABLE "post"`);
        await queryRunner.query(`DROP TYPE "public"."post_view_each_other_answer_enum"`);
        await queryRunner.query(`DROP TYPE "public"."post_retake_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6434de71e37c4f3356d1d7f0fb"`);
        await queryRunner.query(`DROP TABLE "post_answer"`);
        await queryRunner.query(`DROP TYPE "public"."post_answer_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_group_join_request_sender_group"`);
        await queryRunner.query(`DROP INDEX "public"."idx_group_join_request_group_sender"`);
        await queryRunner.query(`DROP TABLE "group_join_request"`);
        await queryRunner.query(`DROP TYPE "public"."group_join_request_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4e21968f2f777c87874d5c5f53"`);
        await queryRunner.query(`DROP TABLE "group_member"`);
        await queryRunner.query(`DROP TYPE "public"."group_member_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f11504860f2f8598340f3092f7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7c5e2858eeb13778bb0ffc9f85"`);
        await queryRunner.query(`DROP TABLE "question_preparation"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_348b427161dc30f5c7bfe6f52c"`);
        await queryRunner.query(`DROP TABLE "question_preparation_collection"`);
        await queryRunner.query(`DROP TABLE "app_config"`);
    }

}
